### PR TITLE
Upgrade usage of NodeJS from 12 to 16

### PR DESCRIPTION
**Pull request by troley**
Ref. https://github.com/semestry/tasks/issues/204#issuecomment-1327291496

## Proposed changes

Updates this action to the recommended NodeJS version.

## Testing

N/A

## Documentation

N/A

### CODE REVIEW

**Review by johanwortel — COMMENTED** [review]
Change version in package.json? And while you're there upgrade the dependencies as well?

**Comment by troley** [comment]
Done. The amount of file changes comes from `yarn upgrade`. Then I also bumped the dependency versions up in the `package.json`.

**Review by johanwortel — CHANGES_REQUESTED** [review]
The is no .gitignore. I suppose it was never built outside GitHub.

**Review by johanwortel — CHANGES_REQUESTED** [review]
You better squash the commits. Now the git history contains all the ignored files.

**Comment by troley** [comment]
> You better squash the commits. Now the git history contains all the ignored files.

Which commits? It will contain the ignored files anyway this once.

**Comment by MikeN123** [comment]
Uh, can we make sure that we are doing the right thing before we are throwing away half the repository?

**Comment by MikeN123** [comment]
https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github explicitely mentions that you check in your node modules, so don't just go around throwing it away without thinking about it.

**Review by MikeN123 — CHANGES_REQUESTED** [review]
See comments.

**Comment by johanwortel** [comment]
> Uh, can we make sure that we are doing the right thing before we are throwing away half the repository?

My mistake. I thought the original (master) version did not contain the node-modules.  I now understand this repository is a runnable system and not a source to build artifacts from.

**Review by johanwortel — APPROVED** [review]

**Review by MikeN123 — APPROVED** [review]

**Comment by Mario2804** [comment]
Can this be merged?

**Comment by johanwortel** [comment]
> Can this be merged?

Yes.
I have already added tag v1.0.0 to tag the old (v1) version.
After the merge the tag v1 has to be put on the new master HEAD. From then on this will be the version used in GitHub workflows.
We can also add a v1.1.0 tag.

**Comment by MikeN123** [comment]
Merged, but it will need some tagging (add v1.1.0, add v1.0.0, move v1 tag)

**Comment by MikeN123** [comment]
VERY IN SYNC WE ARE TODAY JOHAN

**Comment by johanwortel** [comment]
I will continue.

**Comment by johanwortel** [comment]
Done.

**Pull request merged**
